In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/ML & DL COURSE/bank.csv')

In [4]:
dataset.head(10)

age         job   marital  education  ... pdays  previous poutcome deposit
0   59      admin.   married  secondary  ...    -1         0  unknown     yes
1   56      admin.   married  secondary  ...    -1         0  unknown     yes
2   41  technician   married  secondary  ...    -1         0  unknown     yes
3   55    services   married  secondary  ...    -1         0  unknown     yes
4   54      admin.   married   tertiary  ...    -1         0  unknown     yes
5   42  management    single   tertiary  ...    -1         0  unknown     yes
6   56  management   married   tertiary  ...    -1         0  unknown     yes
7   60     retired  divorced  secondary  ...    -1         0  unknown     yes
8   37  technician   married  secondary  ...    -1         0  unknown     yes
9   28    services    single  secondary  ...    -1         0  unknown     yes

[10 rows x 17 columns]

In [5]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [7]:
x = dataset.iloc[:,0:16]
y = dataset.iloc[:,16:17]

In [8]:
x

age          job  marital  education  ... campaign  pdays previous poutcome
0       59       admin.  married  secondary  ...        1     -1        0  unknown
1       56       admin.  married  secondary  ...        1     -1        0  unknown
2       41   technician  married  secondary  ...        1     -1        0  unknown
3       55     services  married  secondary  ...        1     -1        0  unknown
4       54       admin.  married   tertiary  ...        2     -1        0  unknown
...    ...          ...      ...        ...  ...      ...    ...      ...      ...
11157   33  blue-collar   single    primary  ...        1     -1        0  unknown
11158   39     services  married  secondary  ...        4     -1        0  unknown
11159   32   technician   single  secondary  ...        2     -1        0  unknown
11160   43   technician  married  secondary  ...        2    172        5  failure
11161   34   technician  married  secondary  ...        1     -1        0  unknown

[11162 rows x 16 columns]

In [9]:
y

deposit
0         yes
1         yes
2         yes
3         yes
4         yes
...       ...
11157      no
11158      no
11159      no
11160      no
11161      no

[11162 rows x 1 columns]

In [10]:
dataset["job"].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [11]:
dataset["marital"].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [12]:
dataset["education"].unique()

array(['secondary', 'tertiary', 'primary', 'unknown'], dtype=object)

In [13]:
print(type(x),type(y))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>


In [14]:
x = x.values
y = y.values

In [15]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [16]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [17]:
from sklearn.compose import ColumnTransformer # used to convert data to binary format
from sklearn.preprocessing import OneHotEncoder


In [18]:
#ct = ColumnTransformer([("instance name for onehotencoding",onehotencoderfunction,[column index numbers that are to be converted in to binary fotmat])],remainder = "passthrough")
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")
x = ct.fit_transform(x)


In [19]:
x.shape

(11162, 51)

In [20]:
x[0:5]

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 5, 1042, 1, -1, 0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 56, 45, 5, 1467, 1, -1, 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 41, 1270, 5, 1389, 1, -1, 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
        0.

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [40]:
x_train.shape

(8929, 51)

In [41]:
x_test.shape

(2233, 51)

In [42]:
y_train.shape

(8929, 1)

In [43]:
y_test.shape

(2233, 1)

In [44]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [47]:
x_train[0:5]

array([[-0.37172192, -0.45760242, -0.17658264, -0.1589378 ,  1.8452729 ,
        -0.27363591, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772, -0.36485864,  0.86351031, -0.66975544,
        -0.39346051,  1.01614555, -0.69993206, -0.21741017,  0.12621015,
        -0.12621015, -1.05825117,  1.05825117,  0.39003722, -0.39003722,
        -1.60273048, -0.27292594,  1.93439945, -0.30193478, -0.39913565,
        -0.09686471, -0.27410848, -0.17488949, -0.39459853, -0.34910544,
        -0.15930776,  1.70870313, -0.30215554, -0.1931085 , -0.16761389,
        -0.35031555, -0.22657536, -0.32939951,  0.58661881,  0.64941897,
        -0.44565283, -0.90504798, -0.2483547 , -0.56394809, -0.48428507,
        -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, -0.1589378 , -0.54192526,
         3.65449114, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772,  2.7407875 , -1.15806377, -0.66975544,
        -0.39346051,  1.01614

In [48]:
x_test[0:5]

array([[-0.35506564, -0.46571851, -0.16329932, -0.15742303, -0.56407607,
        -0.27405899, -0.19770672,  3.52871184, -0.19276269, -0.44058784,
        -0.18770754, -0.06361417, -0.3502495 ,  0.89812822, -0.71329081,
        -0.39622572, -0.97043245, -0.71329081,  4.77025357,  0.11268723,
        -0.11268723, -1.04348843,  1.04348843,  0.37941391, -0.37941391,
         0.61859723, -0.27311344, -0.5114508 , -0.29341011, -0.38786327,
        -0.11063158, -0.27026248, -0.19150966, -0.4022569 , -0.35666298,
        -0.15891043,  1.75776665, -0.31019338, -0.181218  , -0.18642533,
         2.80376731, -0.21765422, -0.31106004, -1.74928557, -0.01351615,
        -0.43308444, -0.57375418, -0.77542752, -0.51893725,  2.62409874,
         0.62465525],
       [-0.35506564, -0.46571851, -0.16329932, -0.15742303, -0.56407607,
        -0.27405899, -0.19770672, -0.28338953, -0.19276269,  2.26969495,
        -0.18770754, -0.06361417, -0.3502495 ,  0.89812822, -0.71329081,
        -0.39622572,  1.03046